---
apiVersion: v1
kind: Pod
metadata:
  name: "zenko-ui-worker"
spec:
  containers:
  - name: build
    image: {{ images.build }}
    resources:
      requests:
        cpu: "3"
        memory: 4Gi
      limits:
        cpu: "3"
        memory: 4Gi
    env:
    - name: DOCKER_HOST
      value: localhost
    volumeMounts:
    - name: workspace
      mountPath: /home/eve/workspace
  - name: dind-daemon
    image: docker:18.09.2-dind
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-storage
      mountPath: /var/lib/docker
    - name: workspace
      mountPath: /home/eve/workspace
  volumes:
  - name: workspace
    emptyDir: {}
  - name: docker-storage
    emptyDir: {}
