---
version: 0.2

branches:
  feature/*, documentation/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*:
    stage: pre-merge
  development/*:
    stage: post-merge

models:
  - env: &deploy-env
      SCALITY_OCI_REPO: registry.scality.com/scality/zenko-ui
  - env: &keycloak-env
      KEYCLOAK_ROOT: "http://127.0.0.1:8080"
      KEYCLOAK_REALM: "myrealm"
      KEYCLOAK_CLIENT_ID: "myclient"
      KEYCLOAK_USERNAME: "nicolas2bert"
      KEYCLOAK_PASSWORD: "123"
      KEYCLOAK_USER_FULLNAME: "Nicolas Humbert"
  - Git: &clone
      name: fetch source
      repourl: '%(prop:git_reference)s'
      shallow: true
      retryFetch: true
      haltOnFailure: true
  - ShellCommand: &yarn-install
      name: install dependencies
      command: yarn install --frozen-lockfile
      haltOnFailure: true
  - ShellCommand: &yarn-build
      name: build assets
      command: yarn build
      haltOnFailure: true
  - ShellCommand: &docker-build
      name: build docker image
      command: >-
        set -exu;
        docker build --pull -t ${SCALITY_OCI_REPO}:%(prop:commit_short_revision)s .;
      haltOnFailure: True
      env: *deploy-env

stages:
  pre-merge:
    worker: &worker
      type: kube_pod
      path: eve/workers/worker.yaml
      images:
        build: eve/workers/build
        keycloakconfig: eve/workers/keycloakconfig
    steps:
      - Git: *clone
      - ShellCommand: *yarn-install
      - ShellCommand:
          name: run test suite
          command: yarn test
          haltOnFailure: True
      - ShellCommand: *yarn-build
      - ShellCommand: *docker-build
      - ShellCommand:
          name: run end-to-end tests
          command: >-
            docker run -d -p 8383:8383 ${SCALITY_OCI_REPO}:%(prop:commit_short_revision)s;
            set -exu;
            bash wait_for_local_port.bash 8080 40;
            bash wait_for_local_port.bash 8383 40;
            CYPRESS_KEYCLOAK_USER_FULLNAME=${KEYCLOAK_USER_FULLNAME}
            CYPRESS_KEYCLOAK_USERNAME=${KEYCLOAK_USERNAME}
            CYPRESS_KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
            CYPRESS_KEYCLOAK_ROOT=${KEYCLOAK_ROOT}
            CYPRESS_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
            CYPRESS_KEYCLOAK_REALM=${KEYCLOAK_REALM} yarn run cypress:run;
          haltOnFailure: True
          env:
            <<: *deploy-env
            <<: *keycloak-env
  post-merge:
    worker: *worker
    steps:
      - Git: *clone
      - ShellCommand: *yarn-install
      - ShellCommand: *yarn-build
      - ShellCommand: *docker-build
      - ShellCommand:
          name: publish docker image to Scality OCI registry
          command: >-
            set -exu;
            docker login --username "%(secret:harbor_login)s" --password "%(secret:harbor_password)s" ${SCALITY_OCI_REPO};
            docker push ${SCALITY_OCI_REPO}:%(prop:commit_short_revision)s;
          haltOnFailure: True
          env: *deploy-env
